server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev
  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.118.217:8848 # nacos服务地址



txy:
  oss:
    endpoint: cos.ap-guangzhou.myqcloud.com
    secret-id: AKIDsW5PRgXdHdi1906kw1tT2bOA2c07nuXS
    bucket-name: srb-1253645988
    secret-key: x7lHYswkHO3TcWR6UcitnQn5YkgURFnf
