server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev
  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.118.217:8848 # nacos服务地址



txy:
  oss:
    endpoint: 
    secret-id: 
    bucket-name: 
    secret-key: 
