server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456

  redis:
    host: 159.75.118.217
    port: 6379
    database: 0
    password: heyihao
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.118.217:8848 # nacos服务地址

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/atguigu/srb/core/mapper/*.xml

  rabbitmq:
    addresses: 159.75.118.217
    port: 5672
    virtual-host: /srbhost
    username: srb
    password: heyihao

  # 日志级别
#logging:
#  level:
#    root: error