server:
  port: 8120 #服务端口

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-sms

  redis:
    host: 159.75.118.217
    port: 6379
    database: 0
    password: heyihao
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.118.217:8848 # nacos服务地址

  rabbitmq:
    addresses: 159.75.118.217
    port: 5672
    virtual-host: /srbhost
    username: srb
    password: heyihao

#容联云
ronglianyun:
  sms:
    account-id: 8a216da881ad97540181ae18dac00007
    auth-token: f12f8019dc3e4be1b8b2603f9ae2c16d
    app-id: 8a216da881ad97540181ae18dc25000e
    template-id: 1
    server-ip: app.cloopen.com
    server-port: 8883

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时部分
  # 开启服务熔断
  sentinel:
    enabled: true

logging:
  level:
    com.aiguigu.srb.sms.client.CoreUserInfoClient: debug #以什么 级别控制接口
