server:
  port: 8120 #服务端口

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-sms

  redis:
    host: 
    port: 6379
    database: 0
    password: 
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr:  # nacos服务地址

  rabbitmq:
    addresses: 
    port: 5672
    virtual-host: 
    username: 
    password: 

#容联云
ronglianyun:
  sms:
    account-id: 
    auth-token: 
    app-id: 
    template-id: 1
    server-ip: app.cloopen.com
    server-port: 8883

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时部分
  # 开启服务熔断
  sentinel:
    enabled: true

logging:
  level:
    com.aiguigu.srb.sms.client.CoreUserInfoClient: debug #以什么 级别控制接口
